spring:
  datasource:
    url: jdbc:postgresql://postgres-db-instance.c6k558zbt29v.us-east-1.rds.amazonaws.com:5432/postgres
    username: techchallenge
    password: 2I5d3~yiPfab9hr>z
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

aws:
  sqs:
    queue:
      payment:
        endpoint: